/* Source and licensing information for the line(s) below can be found at https://www.law.ox.ac.uk/sites/all/modules/features/oxlaw_livery/js/cookienotice.js. */
(function(e){Drupal.behaviors.cookieNotice={attach:function(o,i){var t=function(o,i){e('body').prepend('<div class="cookie-notice"><p>We use cookies to help give you the best experience on our website. <a href="/cookie-statement">Find out more about cookies.</a></p></div>');e('body').addClass('has-cookie-notice');n()},c=function(o,i){e('body').removeClass('has-cookie-notice')},n=function(){var o=Drupal.settings.cookieNotice.domainroot,e=new Date();e.setDate(e.getDate()+365);document.cookie='hideCookieNotice=TRUE; expires='+e.toUTCString()+';domain='+o+';path=/'},a=function(){var e=!0;cookieSet=document.cookie.indexOf('hideCookieNotice');if(cookieSet==-1){}
else{e=!1};return e};e('body').once(function(){if(a()==!0){t()}
else{c()}})}}}(jQuery));;
/* Source and licensing information for the above line(s) can be found at https://www.law.ox.ac.uk/sites/all/modules/features/oxlaw_livery/js/cookienotice.js. */
/* Source and licensing information for the line(s) below can be found at https://www.law.ox.ac.uk/sites/all/modules/contrib/field_group/field_group.js. */
(function(e){Drupal.FieldGroup=Drupal.FieldGroup||{};Drupal.FieldGroup.Effects=Drupal.FieldGroup.Effects||{};Drupal.FieldGroup.groupWithfocus=null;Drupal.FieldGroup.setGroupWithfocus=function(e){e.css({display:'block'});Drupal.FieldGroup.groupWithfocus=e};Drupal.FieldGroup.Effects.processFieldset={execute:function(i,r,t){if(t=='form'){e('fieldset.fieldset',i).once('fieldgroup-effects',function(i){if(e(this).is('.required-fields')&&e(this).find('.form-required').length>0){e('legend span.fieldset-legend',e(this)).eq(0).append(' ').append(e('.form-required').eq(0).clone())};if(e('.error',e(this)).length){e('legend span.fieldset-legend',e(this)).eq(0).addClass('error');Drupal.FieldGroup.setGroupWithfocus(e(this))}})}}};Drupal.FieldGroup.Effects.processAccordion={execute:function(i,r,t){e('div.field-group-accordion-wrapper',i).once('fieldgroup-effects',function(){var r=e(this),o=!1;r.find('.accordion-item').each(function(i){if(e(this).hasClass('field-group-accordion-active')){o=i}});r.accordion({heightStyle:'content',active:o,collapsible:!0,changestart:function(i,r){if(e(this).hasClass('effect-none')){r.options.animated=!1}
else{r.options.animated='slide'}}});if(t=='form'){var i=!1;r.find('div.field-group-accordion-item').each(function(r){if(e(this).is('.required-fields')&&e(this).find('.form-required').length>0){e('h3.ui-accordion-header a').eq(r).append(' ').append(e('.form-required').eq(0).clone())};if(e('.error',e(this)).length){if(!i){i=e(this).parent().accordion('activate',r)};e('h3.ui-accordion-header').eq(r).addClass('error')}});if(!i){e('.ui-accordion-content-active',i).css({height:'auto',width:'auto',display:'block'})}}})}};Drupal.FieldGroup.Effects.processHtabs={execute:function(i,r,t){if(t=='form'){e('fieldset.horizontal-tabs-pane',i).once('fieldgroup-effects',function(i){if(e(this).is('.required-fields')&&e(this).find('.form-required').length>0){e(this).data('horizontalTab').link.find('strong:first').after(e('.form-required').eq(0).clone()).after(' ')};if(e('.error',e(this)).length){e(this).data('horizontalTab').link.parent().addClass('error');Drupal.FieldGroup.setGroupWithfocus(e(this));e(this).data('horizontalTab').focus()}})}}};Drupal.FieldGroup.Effects.processTabs={execute:function(i,r,t){if(t=='form'){var o=!1;e('fieldset.vertical-tabs-pane',i).once('fieldgroup-effects',function(i){if(e(this).is('.required-fields')&&e(this).find('.form-required').length>0){e(this).data('verticalTab').link.find('strong:first').after(e('.form-required').eq(0).clone()).after(' ')};if(e('.error',e(this)).length){e(this).data('verticalTab').link.parent().addClass('error');if(!o){Drupal.FieldGroup.setGroupWithfocus(e(this));e(this).data('verticalTab').focus();o=!0}}})}}};Drupal.FieldGroup.Effects.processDiv={execute:function(i,r,t){e('div.collapsible',i).once('fieldgroup-effects',function(){var i=e(this),t=e('span.field-group-format-toggler:first',i),r=e('<a class="field-group-format-title" href="#"></a>');r.prepend(t.contents());if(e(this).is('.required-fields')&&e(this).find('.form-required').length>0){r.append(' ').append(e('.form-required').eq(0).clone())};r.appendTo(t);r.click(function(){var r=i.get(0);if(!r.animating){r.animating=!0;var t=i.hasClass('speed-fast')?300:1000;if(i.hasClass('effect-none')&&i.hasClass('speed-none')){e('> .field-group-format-wrapper',r).toggle()}
else if(i.hasClass('effect-blind')){e('> .field-group-format-wrapper',r).toggle('blind',{},t)}
else{e('> .field-group-format-wrapper',r).toggle(t)};r.animating=!1};i.toggleClass('collapsed');return!1})})}};Drupal.behaviors.fieldGroup={attach:function(i,r){r.field_group=r.field_group||Drupal.settings.field_group;if(r.field_group==undefined){return};e.each(Drupal.FieldGroup.Effects,function(t){var o=t.toLowerCase().replace('process','');if(r.field_group[o]!=undefined&&e.isFunction(this.execute)){this.execute(i,r,r.field_group[o])}});e('.fieldset-wrapper .fieldset > legend').css({display:'block'});e('.vertical-tabs fieldset.fieldset').addClass('default-fallback');e('.group-wrapper .horizontal-tabs-panes > fieldset',i).once('group-wrapper-panes-processed',function(){var i='field_group-'+e(this).attr('id');e(this).attr('id',i)});e('.group-wrapper ul li').once('group-wrapper-ul-processed',function(){var i=e(this).index();e(this).children('a').click(function(){var r=e('.group-wrapper fieldset').get(i),t=e(r).attr('id').replace(/^field_group-/,'').split(' ')[0];window.location.hash=t})})}}})(jQuery);;
/* Source and licensing information for the above line(s) can be found at https://www.law.ox.ac.uk/sites/all/modules/contrib/field_group/field_group.js. */
/* Source and licensing information for the line(s) below can be found at https://www.law.ox.ac.uk/sites/all/modules/contrib/disqus/disqus.js. */
;var disqus_shortname='',disqus_url='',disqus_title='',disqus_identifier='',disqus_developer=0,disqus_def_name='',disqus_def_email='',disqus_config;(function(s){Drupal.behaviors.disqus={attach:function(u,i){s('body').once('disqus',function(){if(i.disqus||!1){disqus_shortname=i.disqus.domain;disqus_url=i.disqus.url;disqus_title=i.disqus.title;disqus_identifier=i.disqus.identifier;disqus_developer=i.disqus.developer||0;disqus_def_name=i.disqus.name||'';disqus_def_email=i.disqus.email||'';disqus_config=function(){if(i.disqus.language||!1){this.language=i.disqus.language};if(i.disqus.remote_auth_s3||!1){this.page.remote_auth_s3=i.disqus.remote_auth_s3};if(i.disqus.api_key||!1){this.page.api_key=i.disqus.api_key};if(i.disqus.sso||!1){this.sso=i.disqus.sso};if(i.disqus.callbacks||!1){for(var d in i.disqus.callbacks){for(var e=0;e<i.disqus.callbacks[d].length;e++){var a=i.disqus.callbacks[d][e].split('.'),s=window;for(var u=0;u<a.length;u++){s=s[a[u]]};if(typeof s==='function'){this.callbacks[d].push(s)}}}}};jQuery.ajax({type:'GET',url:'//'+disqus_shortname+'.disqus.com/embed.js',dataType:'script',cache:!1})};if(i.disqusComments||!1){disqus_shortname=i.disqusComments;jQuery.ajax({type:'GET',url:'//'+disqus_shortname+'.disqus.com/count.js',dataType:'script',cache:!1})}})}}})(jQuery);;
/* Source and licensing information for the above line(s) can be found at https://www.law.ox.ac.uk/sites/all/modules/contrib/disqus/disqus.js. */
